# Generated by Django 2.1.5 on 2019-01-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qauser',
            name='user_ptr',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='word',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='answer',
            name='right_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='QaUser',
        ),
    ]
